name:                CEREScript-SS-BI
version:             0.7.0.0
github:              "HolosDev/CEREScript-SS-BI"
license:             OtherLicense
author:              "YongJoon Joe"
maintainer:          "Holos Works <developer@holos.dev>"
copyright:           "2019-2020 Holos Works / PPUZZL Group"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/HolosDev/CEREScript-SS-BI#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- parallel
- random-adaptor
- splitmix
- text
- text-show
- text-trie
- CEREScript-SS
- CEREScript-SS-Parser

default-extensions:
- OverloadedStrings
- RecordWildCards

library:
  source-dirs: src

executables:
  CEREScript-SS-BI-exe:
    main:                Main.hs
    source-dirs:         apps/init
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-SS-BI
  CEREScript-SS-BI-MT-exe:
    main:                Main.hs
    source-dirs:         apps/money_transfer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-SS-BI

tests:
  CEREScript-SS-BI-test:
    main:                Spec.hs
    source-dirs:         tests/Spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-SS-BI
