name:                CEREScript-Core01-BI
version:             0.3.1.0
github:              "HolosDev/CEREScript-Core01-BI"
license:             OtherLicense
author:              "YongJoon Joe"
maintainer:          "YongJoon Joe <developer@quietjoon.net>"
copyright:           "2019-2020 Holos Works/MiRiS Project"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/HolosDev/CEREScript-Core01-BI#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- splitmix
- text
- text-show
- CEREScript-Core01

default-extensions:
- OverloadedStrings
- RecordWildCards

library:
  source-dirs: src

executables:
  CEREScript-Core01-BI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-Core01-BI

tests:
  CEREScript-Core01-BI-test:
    main:                Spec.hs
    source-dirs:         tests/Spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-Core01-BI
