resolver: lts-14.27

packages:
- .
# In development
#- /AoDw/CEREScript/CEREScript-SS00
#- /AoDw/CEREScript/CEREScript-SS00-Parser

extra-deps:
- text-trie-0.2.5.0
- splitmix-0.0.4
#- git: https://gitlab.com/holosdev/CEREScript-SS
- github: HolosDev/CEREScript-SS
  commit: ccc21ca5ed498b2dfcc0845831da5e9c734fb3da
- github: HolosDev/CEREScript-SS-Parser
  commit: b34bc879fb18b9cd2c16f4b074b1aa56a00806b7
- github: QuietJoon/random-adaptor
  commit: f2f7578027ec2a855a59f7a10f4afeaa0f870b37
