resolver: lts-14.27

packages:
- .
#- /AoDw/CEREScript/CEREScript-Core01

extra-deps:
- text-trie-0.2.5.0
- splitmix-0.0.4
- github: HolosDev/CEREScript-Core01
#- git: https://gitlab.com/holosdev/CEREScript-Core01
  commit: 1ba4d2d8707c6e915625204f3d74279ed7104bfd
- github: QuietJoon/random-wrapper
  commit: 2515a5a0fde0e155097fe5d35b4f90c761e86e04
