resolver: lts-14.27

packages:
- .
# In development
#- /AoDw/CEREScript/CEREScript-SS00
#- /AoDw/CEREScript/CEREScript-SS00-Parser

extra-deps:
- text-trie-0.2.5.0
- splitmix-0.0.4
#- git: https://gitlab.com/holosdev/CEREScript-SS
- github: HolosDev/CEREScript-SS
  commit: 655ab9d0481f5543ed33ab926067c134b64271a8
- github: HolosDev/CEREScript-SS-Parser
  commit: 260957c5a756063a53bfd03386c131e099bd6357
- github: QuietJoon/random-adaptor
  commit: f2f7578027ec2a855a59f7a10f4afeaa0f870b37
